### ISSUE TITLE
Deprecation warning with php 8.2

### ISSUE THREAD

**Issue by bagong** [drush-ops/drush-launcher#102]
Hi,

using drush(-launcher) as advised produces a deprecation warning on my system (dl-0.10.., D10, drush 3.14, php 8.2) reading something like (quoted from bad memory):

`php warning: deprecated use of static in line 1973`

Thanks for your consideration
.r.

**Comment by back-2-95** [comment]
Hi, I can confirm. I use Wodby stack with their PHP 8.2 image. Image has drush-launcher and this error comes for every drush command. I using Drush 10.4 from my project (vendor/bin/drush) this does not happen as it has newer webmozarts/assert package: https://github.com/webmozarts/assert/issues/274

**Comment by gapple** [comment]
I've created a pull request to upgrade the necessary dependency versions.  
If you would like to build an updated launcher locally:
- Clone the fixed drush-launcher branch
- run `$ composer run-script box-install && composer run-script box-compile`
- replace your current `drush` executable with the new `drush.phar`

**Comment by back-2-95** [comment]
@gapple I did what you instructed and here is the result (after creating new drush.phar):

- first I run existing drush-launcher and you can see the deprecation message
- then I copy new drush.phar over existing one
- rerun and deprecation message is gone

```
wodby@php.container:/var/www/html/drush-launcher $ /usr/local/bin/drush --version
Drush Launcher Version: 0.10.1
[03-Feb-2023 06:38:54 UTC] PHP Deprecated:  Use of "static" in callables is deprecated in phar:///usr/local/bin/drush/vendor/webmozart/assert/src/Assert.php on line 1973

Deprecated: Use of "static" in callables is deprecated in phar:///usr/local/bin/drush/vendor/webmozart/assert/src/Assert.php on line 1973
[03-Feb-2023 06:38:54 UTC] PHP Deprecated:  Use of "static" in callables is deprecated in phar:///usr/local/bin/drush/vendor/webmozart/assert/src/Assert.php on line 1973

Deprecated: Use of "static" in callables is deprecated in phar:///usr/local/bin/drush/vendor/webmozart/assert/src/Assert.php on line 1973
Drush Commandline Tool 11.4.0
wodby@php.container:/var/www/html/drush-launcher $ cp drush.phar /usr/local/bin/drush
wodby@php.container:/var/www/html/drush-launcher $ /usr/local/bin/drush --version
Drush Launcher Version: be1945c
Drush Commandline Tool 11.4.0
```

**Comment by back-2-95** [comment]
@webflo ^^

**Comment by webflo** [comment]
Thanks to all. Released as https://github.com/drush-ops/drush-launcher/releases/tag/0.10.2
