### ISSUE TITLE
Could not find Drupal in the current path

### ISSUE THREAD

**Issue by yamlfd** [drush-ops/drush-launcher#12]
Tried v 0.2.2 and 0.2.4, but everytime I run drush --version I get a message 

> /srv/www/foo# drush --version
> Drush Shim Version: 0.2.2
> Could not find Drupal in the current path.

That is the path where Drupal is...

**Comment by weitzman** [comment]
Right now, you have to launch your drush commands from your drupal project, or pass in the project's path via --root=/path/to/drupal. If you are already in the Drupal root, then I dont know what could be wrong. Try with --debug.

**Comment by yamlfd** [comment]
This outputs are not helpful... this is Drupal 7.54 in the root folder.

```
root@foo:/srv/www/web1/html# drush --debug
Drush Shim Version: 0.2.4
ROOT: /srv/www/web1/html
Could not find Drupal in the current path.
root@foo:/srv/www/web1/html# drush --root=/srv/www/web1/html
Could not find Drupal in the current path.
root@foo:/srv/www/web1/html# drush --debug --root=/srv/www/web1/html
Drush Shim Version: 0.2.4
ROOT: /srv/www/web1/html
Could not find Drupal in the current path.
root@foo:/srv/www/web1/html# ls
CHANGELOG.txt      INSTALL.pgsql.txt   LICENSE.txt      UPGRADE.txt    files      install.php  profiles  themes      xmlrpc.php
COPYRIGHT.txt      INSTALL.sqlite.txt  MAINTAINERS.txt  authorize.php  includes   misc         scripts   update.php
INSTALL.mysql.txt  INSTALL.txt         README.txt       cron.php       index.php  modules      sites     web.config
root@foo:/srv/www/web1/html#
```

How can we debug this? Cannot run without drush :)

**Comment by weitzman** [comment]
I have only used the shim with drupal 8 and a site-local drush installed. if you dont have a site local drush, you cant use this shim, you need to use drush directly.

**Comment by webflo** [comment]
@yamlfd Is you D7 site build with composer?

**Comment by yamlfd** [comment]
No, not at all. I just followed the installation guide "Install/Upgrade a global Drush" at http://docs.drush.org/en/8.x/install/ . The title Install/Upgrade a global Drush makes me thinking this is not site-local and is global to the operating system.

**Comment by weitzman** [comment]
FYI, The Drush 8 docs that you link to dont mention this project at all. Only Drush master docs do.
