### ISSUE TITLE
Error when using Drush Shim

### ISSUE THREAD

**Issue by cmcintosh** [drush-ops/drush-launcher#19]
PHP Fatal error:  Uncaught Error: Call to undefined function drush_set_option() in phar:///bin/drush/bin/drush.php:153
Stack trace:
#0 /bin/drush(10): require()
#1 {main}
  thrown in phar:///bin/drush/bin/drush.php on line 153

**Comment by webflo** [comment]
Looks like your Drupal site has no local drush

**Comment by cmcintosh** [comment]
I am trying to install this on a vagrant box.  Is it no longer possible to just have drush available system-wide? seems very wasteful to have multiple copies on a dev box.

Side note, the project has drush, but the path looks like: /vendor/drush/drush not sure if that is normal

**Comment by cmcintosh** [comment]
double checked.  I have drush system-wide accessible on my windows host system.  Also, checked in the project and i have a copy of drush.  I had ran composer global in the guest box, but have removed it.

Both with it there and without im getting the same error

**Comment by cmcintosh** [comment]
removing drush from the project + readding to see if I can sort things.

**Comment by cmcintosh** [comment]
so looks like i have the files its asking for:
'local' => [
    $drupalRoot . '/../vendor/drush/drush/includes/preflight.inc',
    $drupalRoot . '/../vendor/drush/drush/includes/context.inc'
  ],

**Comment by webflo** [comment]
The point of drush-shim is to get rid of the global Drush installation, since its not sustainable for Drush to support multiple version of Drupal core. You have to add drush to your project. Use Drush 8.x for Drupal 8.3.x and Drush 9.x for Drupal 8.4.x.
