### ISSUE TITLE
Document how to update the launcher

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush-launcher#22]
We depend on phar-updater but it is not clear how to use it.

**Comment by webflo** [comment]
<code>drush self-update</code> should work.

**Comment by webflo** [comment]
https://github.com/humbug/phar-updater/pull/51 is related

**Comment by webflo** [comment]
``self-update`` will work, but it takes up to 12 hours until the release is available.

**Comment by webflo** [comment]
``self-update`` from webflo/drush-shim to drush/drush-launcher is not supported.

**Comment by weitzman** [comment]
Thanks for all that info ... Lets leave this issue open for docs. I'm
thinking about how to explain that this command updates the launcher
and not drush itself. Maybe we should rename the command to drush
launcher-update or similar.
