### ISSUE TITLE
encoding problem with downloaded file

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush-launcher#26]
The file I downloaded with wget according to the README instructions has this in it:

```
 * @copyright  Copyright (c) 2015 P√°draic Brady (http://blog.astrumfutura.com)
```

That looks like an encoding error.

**Comment by webflo** [comment]
Could you check you shell encoding/locale settings or update wget? Looks all valid in PhpStorm.

![drush_phar_encoding](https://user-images.githubusercontent.com/123946/29880918-605e8a8c-8da9-11e7-9dc1-d96747c0be1a.jpg)

**Comment by joachim-n** [comment]
Ah, it was my text editor opening it with the wrong encoding.

Sorry for the noise!

**Comment by webflo** [comment]
Np :)
