### ISSUE TITLE
Permit usage without Drupal

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush-launcher#29]
At present, if I were to execute `drush @alias uli` in a directory containing `vendor/bin/drush`  that did not have a Drupal root (anywhere), the launcher would be unable to detect my drush installation and execute the command.

The launcher should be able to detect a project version of drush even if that project does not contain Drupal root.

**Comment by weitzman** [comment]
Not only does the launcher not support that, neither does Drush itself (at this time). A command must exist locally in order to get to the point where remote dispatch happens. Thats a bug that can hopefully be fixed. As for the launcher, I guess it could hand of to Drush in the absence of Drupal.

**Comment by mortenson** [comment]
In my opinion the ideal UX for aliases and Drush Launcher is that you can use them from any directory, similar to how aliases currently work with global Drush. If I have to `cd` to a specific directory use aliases it makes them significantly less useful to me (may as well have a separate binary in that directory like `./drush`, at that point).

I wonder if Drush Launcher could have a configurable fallback path to a Drush binary, to be used if a local Drush cannot be found. So globally `drush` would still run the launcher, but if it couldn't locate Drupal it would optionally fall back to a global variable like `$DRUSH_LAUNCHER_FALLBACK`.

**Comment by weitzman** [comment]
@mortenson thats how the launcher worked for a little while. i didn't like it though because i find that very hard to support. folks will have no clue whats launching their site local drush. and they wont be able to keep track of what versions are running for each component.

Lets track alias support in Launcher at #2. Help wanted.

**Comment by weitzman** [comment]
FYI, we actually implemented the DRUSH_LAUNCHER_FFEDBACK idea from above. See README.
