### ISSUE TITLE
Can't install on Travis CI

### ISSUE THREAD

**Issue by mitrpaka** [drush-ops/drush-launcher#31]
Hi,
I am trying to replace webflo/drush-shim with drush/drush-launcher as recommended. On Travis CI builds I am now experiencing following dependency issue (using composer global require drush/drush-launcher):

```
Using version ^0.4.2 for drush/drush-launcher
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: webflo/drupal-finder[1.0.0, 0.4.2].
    - Can only install one of: webflo/drupal-finder[1.0.0, 0.4.2].
    - Can only install one of: webflo/drupal-finder[1.0.0, 0.4.2].
    - drush/drush-launcher 0.4.2 requires webflo/drupal-finder ^1.0 -> satisfiable by webflo/drupal-finder[1.0.0].
    - Installation request for drush/drush-launcher ^0.4.2 -> satisfiable by drush/drush-launcher[0.4.2].
    - Installation request for webflo/drupal-finder (locked at 0.4.2) -> satisfiable by webflo/drupal-finder[0.4.2].
```

webflo/drupal-finder, 1.0.0 is included through dependencies in the project's vendor directory already.

Any idea what could cause this issue and how to resolve it?

**Comment by weitzman** [comment]
Are you using drush.phar? You should, per the drush-launcher readme.

**Comment by mitrpaka** [comment]
Yes, using drush.phar as recommended in readme. 

It turned out to be Travis CI caching issue. If you have cached composer directory in Travis CI, cache should be cleared once webflo/drush-shim replaced with drush/drush-launcher. Otherwise above dependency issue will occur.

As webflo/drush-shim package is deprecated and use of drush/drush-launcher is recommended as replacement, it perhaps could be good to add to the drush-launcher readme as a note for Travis CI users.

**Comment by webflo** [comment]
Nobody else reported this issue. It will resolve itself over time because its a cache issue.
