### ISSUE TITLE
Add support for installing drush-launcher with homebrew [feature request]

### ISSUE THREAD

**Issue by greylabel** [drush-ops/drush-launcher#34]

**Comment by webflo** [comment]
I am a homebrew user myself and like the idea. But i have to look into how to deal with the existing drush formular. https://github.com/Homebrew/homebrew-php/blob/master/Formula/drush.rb

I think its possible to mark it as conflicts and add a formular for drush-launcher.

**Comment by webflo** [comment]
@greylabel Please review https://github.com/Homebrew/homebrew-php/pull/4549 Thanks!

**Comment by danepowell** [comment]
It looks like that PR was merged, so brew support should now be available. Should this issue be closed?

**Comment by weitzman** [comment]
Yes. I'll add to README now.

**Comment by oxyc** [comment]
Homebrew PHP is now deprecated.

**Comment by webflo** [comment]
I know, i removed the install instructions in https://github.com/drush-ops/drush-launcher/commit/46a8ee0eb2ef557d2da933caa8a58363956937c2 until we have a new formula in homebrew-core
