### ISSUE TITLE
Specify somewhere (anywhere!) that it is incompatible with Drupal 7 installs

### ISSUE THREAD

**Issue by TynanFox** [drush-ops/drush-launcher#36]
In the documentation on installation, please state somewhere that Drush Launcher is  ONLY compatible with Drupal 8 sites!

I wasted a few too many hours today wrestling with Drush Launcher since I am running D7 as well as D8 sites. Since Drush 9 is incompatible with D7, I would need to install Drush 8 on D7 and Drush 9 on D8. Using local installs with Drush Launcher seemed like a perfect solution. 

However, one of the checks in the DrupalFinder dependency of Drush Launcher determines that the site is running Drupal 8. If the site is running Drupal 7, the launcher simply terminates with very little explanation as to why. The error it produces simply says "The Drush Launcher could not find a Drupal site to operate on." Which is a particularly maddening error if you have your root set to a perfectly valid D7 installation. :)

I mean, it also raises the question - why not work with D7 installations? But that's a separate issue. My goal here is just to ask the maintainer to PLEASE note somewhere in the documentation that this can only be used with Drupal 8 installations. Thank you in advance. :)

**Comment by webflo** [comment]
Drupal Finder can detect Drupal 7 sites with site local drush but they have to follow the drupal-composer layout.

**Comment by webflo** [comment]
Take a look at https://github.com/webflo/drupal-finder/blob/master/tests/Drupal7FinderTest.php for more information.

**Comment by TynanFox** [comment]
Unfortunately many of my sites do not follow the drupal-composer layout. :( They were built by others who did not use that. 

Perhaps just mentioning then that for use with Drupal 7 sites, the site must follow that layout.

**Comment by weitzman** [comment]
Maybe our error message could mention that a site-local Drush is required.

**Comment by TynanFox** [comment]
Here's the thing. I DID install a site-local Drush.

Now please note that I had originally built my site without composer so it doesn't follow the normal drupal-composer layout. 

But I DID add composer and require drush as a site local dependency. 

But because my full site doesn't follow the drupal-composer layout, the launcher wouldn't verify my site as a Drupal 7 install.

**Comment by webflo** [comment]
@TynanFox Where is the composer.json located? In the Drupal root folder?

**Comment by DicksB** [comment]
Yeah, I'm having the same trouble. We're beginning to build Drupal 8 sites, but we have a lot of Drupal 7 sites that have been built over the past ~7 years without using composer. I'm trying to retrofit site-local drush onto them, but no luck.

My layout is:

Project root
* composer.json
* docroot
  * sites
    * (various multisite directories)
* vendor
  * drush

**Comment by weitzman** [comment]
You can't "retrofit" like that. Composer does more than just put files into directories. It also builds an autoloader. In your layout, the autoloader contains all of Drush's classes but none from Drupal. Thats not going to work.

One we get #37, you can specify a global drush to handle these D7 sites and not bother retrofitting them.

**Comment by DicksB** [comment]
Excellent, thanks.

**Comment by webflo** [comment]
Should work with https://github.com/drush-ops/drush-launcher/commit/427bdfc2656f0dddc318781013e9665596919773
