### ISSUE TITLE
Psr\Log\AbstractLogger not found only when using launcher

### ISSUE THREAD

**Issue by karlshea** [drush-ops/drush-launcher#43]
```
$ composer --version
Composer version 1.6.1 2018-01-04 14:45:25

$ php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

/var/www/demo/repo/web$ drush --version
Drush Launcher Version: 0.5.0
PHP Fatal error:  Class 'Psr\Log\AbstractLogger' not found in /var/www/demo/repo/vendor/drush/drush/lib/Drush/Log/Logger.php on line 31

/var/www/demo/repo/web$ ../vendor/bin/drush --version
 Drush Version   :  8.1.15
```

Any other information I can provide? Or could it be I set something up wrong? I used the drupal-composer/drupal-project template to create the project.

psr/log is in vendor, and composer installed v1.0.2.

**Comment by webflo** [comment]
It could be related to https://github.com/composer/composer/pull/6976.
Please run composer dump-autoload with composer 1.5.x
Karl Shea <notifications@github.com> schrieb am Fr. 5. Jan. 2018 um 00:52:

**Comment by karlshea** [comment]
Updated to composer 1.6.2 (released today), ran `composer dump-autoload` and it appears to have fixed it. Thank you!

**Comment by pixelwhip** [comment]
I ran into this as well. Same solution worked for me. In my case it was updating from 1.6.1 -> 1.6.4 
```composer self-update
composer dump-autoload```
