### ISSUE TITLE
Allow to invoke global Drush 8 for Drupal 7 sites

### ISSUE THREAD

**Issue by Frando** [drush-ops/drush-launcher#46]
Hi,
on my localhosts, I'm working on both Drupal 7 and Drupal 8 projects. Currently, I have drush 8 installed globally and for each Drupal 8 project a local Drush 9 via composer. I have also drush-launcher installed. I aliased drush to a drush8 command. It would be great if drush launcher could detect if I am in a Drupal 7 oder Drupal 8 project, and if the former, invoke a global drush 8 installation, and if the latter, invoke the local Drush 9.
Best,
Franz

**Comment by weitzman** [comment]
See Fallback - https://github.com/drush-ops/drush-launcher#fallback

**Comment by Frando** [comment]
Missed that, thanks.
