### ISSUE TITLE
Consider changing the installation command so that it will always install the latest version

### ISSUE THREAD

**Issue by frederickjh** [drush-ops/drush-launcher#51]
Please consider changing the installation command so that it will always install the latest version after a new release.

The following command will parse out the link to the latest version and download it. This can be useful when this is scripted for deployments, so it  does not need to be changed for each new release.

`curl -s -L https://github.com/drush-ops/drush-launcher/releases/latest | egrep -o '/drush-ops/drush-launcher/releases/download/[0-9.]*/drush.phar' | wget --base=http://github.com/ -i - -O drush.phar`

[More info on this command string](https://stackoverflow.com/a/27869453/6079319)

**Comment by weitzman** [comment]
uses wget AND curl? odd.

i'm ambivalent about adding this.

**Comment by frederickjh** [comment]
Explanation:

`curl -s -L` is to silently download the latest release HTML (after following redirect)

`egrep -o` '...' uses regex to find the file you want

`wget --base=http://github.com/ -i -` converts the relative path from the pipeline to absolute URL

and `-O` scollector sets the desired file name.

@weitzman Can you craft the command using only one of them so that it downloads the latest release?

**Comment by nicolas-san** [comment]
@weitzman @frederickjh 
following this https://help.github.com/en/github/administering-a-repository/linking-to-releases
just using 
`wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar`
works fine

**Comment by weitzman** [comment]
I updated to use the evergreen url for download. lets use a new use for any PATH changes.
