### ISSUE TITLE
Global launcher should assume --local config

### ISSUE THREAD

**Issue by simesy** [drush-ops/drush-launcher#56]
Global launcher solves the problem where modern Drupal sites ship with their own drush version. If i have drush in the `vendor` directory of the current project, then great.

This provides great DX: "just run drush".
Not, "add this to your bashrc, or just run ./vendor/bin/drush".

Following this logic, the project might also ship with project-specific config. Aliases and options. This gives me the ability to say "just run drush @dev" and every projects is the same, regardless of the hosting. Outside of the project directory, I don't want anyone hit @dev and get this project. Inside the project, I don't want developers to deal with groups in their aliases. `drush sa` should list @dev @stg @prod etc, and that's it. 

Two solutions I can think of:

- global launcher could pass --local by default, if it find a project-level drush
- global launcher could look for a drush.wrapper where i can set --local

In the drush 8.x project, perhaps it could load drushrc earlier, at least to look for --local, but I fear this is probably a fragile order of operations.

**Comment by weitzman** [comment]
We used to do pass --local by default. It caused some surprises so we removed that. I dont think launcher is going to solve this. I suggest adding a bash alias that adds --local.

**Comment by simesy** [comment]
I used to have a bash alias to ./vendor/bin/drush among other things, but drush launcher solved that. It's mostly been great because onboarding devs doesn't require adding and removing bash aliases (which tends to cause them suprises when it effects other projects.

It would be fantastic to have some sort of switch in some sort of file in the repo that drush launcher could look for.

**Comment by simesy** [comment]
Is there a chance of getting drush launcher to look for a drush.wrapper in the project root and call that if so?

**Comment by simesy** [comment]
Glad to see drush.wrapper gone then, that always seemed odd.

I am seeing aliases from other projects during the sitealias.inc discovery, it sees multiple @dev aliases because it looks globally and some global aliases are called @dev (since it doesn't know --local yet) and then it sets the wrong one in cache. Possibly this simply a different bug that can be fixed on drush project?

**Comment by simesy** [comment]
Oh, i can't delete all aliases since Platform.sh CLI is adding them automatically. Maybe I could ask them to change that functionality, but it seems like drush should prefer mine.

**Comment by weitzman** [comment]
Drush9 doesn't discover global aliases by default. Are you using Drush 8? Consider an upgrade for Drupal7 and Drupal8 sites.

**Comment by simesy** [comment]
Ahh, yes drush 8. Ok sounds good.

**Comment by simesy** [comment]
I moved to Drush 9 and this worked for a while, but then it seems that https://github.com/drush-ops/drush-launcher/pull/28/commits/3ded39b8252c24148cb52cdf106cfd633b17fac2 removed this feature?

**Comment by webflo** [comment]
We should not implement **local** or **global** in the drush-launcher. The behavior of drush should not vary if drush is invoked by the drush-launcher or directly (./vendor/bin/drush ...). It will cause a lot of confusion.

I think we should move this over to the drush issue queue.

**Comment by simesy** [comment]
Turns out my ~/.drush/drush.yml had:
```
drush:
    paths:
        alias-path:
            - '${env.home}/.drush/site-aliases'
```
