### ISSUE TITLE
Trouble with remote debugging

### ISSUE THREAD

**Issue by ajmichels** [drush-ops/drush-launcher#64]
I am trying to debug some code using Xdebug and PHPStorm but I am having trouble configuring PHPStorm to correctly map the drush launcher phar file to a local file that PHPStorm can inspect. Without this mapping xdebug/PHPStorm seems to get confused about the execution path and never gets to the code I am trying to debug, it just hangs.

I have tried added the phar file locally as an external library but when I do this it doesn't appear as a mappable path.

I have tried adding the source code for drush and mapping `drush` file to the drush launcher phar file. That doesn't work.

I have tried pulling the drush launcher source code down and mapping the `bin/drush` file to the phar file on the remote. That doesn't work.

Any suggestions.

**Comment by webflo** [comment]
Is this still an issue? I think its easier if you don't use the par file for debugging and checkout the project from git.

**Comment by webflo** [comment]
... and make sure you have ```DRUSH_ALLOW_XDEBUG=1``` in your environment.
