### ISSUE TITLE
DRUSH 9 SQL:CLI not working with XDEBUG Enabled

### ISSUE THREAD

**Issue by sean-e-dietrich** [drush-ops/drush-launcher#68]
A few different people have confirmed that when XDebug is enabled  and running commands through the launcher for Drush 9 the command hangs up and doesn't actually pass through to the database.

The biggest offender seems to be `sql:cli` so far.

If you access drush directly through the vendor/bin/drush executable then it works but when using the drush launcher it seems to hang up and not make a connection to the database.

When you disable xdebug then this works.

For Reference: https://github.com/docksal/docksal/issues/795

**Comment by weitzman** [comment]
Try with latest Drush 9.6 release (or master). We are now using Symfony Process to execute calls like `mysql`.

**Comment by weitzman** [comment]
I tested with Drush 9.6.0-rc3 and could not reproduce the problem. I did see it with prior versions of Drush so I think this is fixed.

**Comment by webflo** [comment]
@weitzman Is this another related issue? https://github.com/drush-ops/drush/issues/3309
