### ISSUE TITLE
How to set path to PHP version to use with site local Drush?

### ISSUE THREAD

**Issue by frederickjh** [drush-ops/drush-launcher#71]
I have Drush Launcher installed and it is working and finding my site local Drushes. However I have one site that I still need to used Drush 8 on with php 5.6. I have installed a site local Drush 8 for this site. Drush launcher find and run the site local, however it uses the default php of 7.1. Several versions of php are available.

If I include the path on the command line to php 5.6 and set the DRUSH_PHP on the command line to the same path to php, I can get the the site local drush 8 to run with php 5.6.

I tried hacking the drush.launcher that came with Drush 8 to set the path to php but it appears that when launching Drush with this project, drush-launcher, that this file is not run. and it ends up using the default PHP 7.1.

I know in a previous issue it was stated that Drush was out of the business of setting up the php environment as it was too complex to maintain this. However it would be nice if there was a way to set the php version for site local versions of Drush. Which it appears that there is not unless you count typing out a mile long command every time to set the exact path to the php binary, set DRUSH_PHP and the exact path to the Drush binary to use.

**Comment by leymannx** [comment]
Is the site you need to use Drush 8 with managed by Composer? If not, you may want to remove the site local Drush 8 again and instead simply export `DRUSH_LAUNCHER_FALLBACK` in your `.bashrc` or similar.

    export DRUSH_LAUNCHER_FALLBACK="/path/to/php5.6-cli /path/to/drush8

Alternatively you can also install a global `drush8` command like illustrated in this post: [[Drupal Answers] Having multiple Drush instances for different core versions](https://drupal.stackexchange.com/a/267520/15055).

**Comment by leymannx** [comment]
And if it's only for one site, an alias in your `.bash_aliases` might be fine as well.

    alias drush8='/path/to/php5.6-cli /path/to/old/project/vendor/bin/drush'

**Comment by frederickjh** [comment]
@leymannx I have tried the export DRUSH_LAUNCHER_FALLBACK option and this is also a difficult option as quoting in environmental variable is weird. What works on the command line does not always work in the environmental variable. I have found it easiest to write a small bash script that adds the path to the correct php version to the front of the $PATH, sets DRUSH_PHP, then runs drush by specifying the absolute path to the correct php version and the absolute path to Drush.

I already have a global Drush 8 install and this works with the bash script as described above.

I take it from your answer that Drush 8 does not support being site local run with the `drush-launcher`, in that you cannot set the path to the php version when run this way?

**Comment by leymannx** [comment]
I use `DRUSH_LAUNCHER_FALLBACK` exactly like that and for me it works. But there was a typo in my export command missing the closing quote.

**Comment by webflo** [comment]
Indeed, there is no direct support for using a different PHP version. But drush-launcher uses the same PHP binary to run the command in the selected site.

If you call the drush launcher with the PHP version you want to use on the given site, it should work.

I use phpenv for dealing with multiple php versions. Every site gets and .php-version file. https://github.com/madumlao/phpenv

**Comment by frederickjh** [comment]
@leymannx I have never been able to get to work to use the version of PHP what I set using `DRUSH_LAUNCHER_FALLBACK´  would you mind posting what you are using so I can see how you do the quoting. I am guessing that this is where it is  failing.

**Comment by frederickjh** [comment]
@webflo Thanks for pointing me to phpenv. I just took a look at it and it looks like you need to build all the versions of php. I am using this an a Cpanel jailed shell where I already have the php version available. Do you know if it is possible to configure phpenv to use the Cpanel paths to php instead of having to build php versions?

**Comment by frederickjh** [comment]
@webflo I just opened an [issue](https://github.com/madumlao/phpenv/issues/21) in the phpenv issue queue about using pre-build versions of PHP.

**Comment by webflo** [comment]
@frederickjh No need to build versions with phpenv. You can create your own symlinks in the versions folder. I use it in conjunction with homebrew.

```
ls -l /usr/local/opt/phpenv/versions
total 0
lrwxr-xr-x  1 fweber  admin  22 Oct 26 00:00 5.6 -> /usr/local/opt/php@5.6
lrwxr-xr-x  1 fweber  admin  22 Oct 26 00:00 7.0 -> /usr/local/opt/php@7.0
lrwxr-xr-x  1 fweber  admin  22 Oct 26 00:00 7.1 -> /usr/local/opt/php@7.1
lrwxr-xr-x  1 fweber  admin  22 Dec 11 13:09 7.2 -> /usr/local/opt/php@7.2
lrwxr-xr-x  1 fweber  admin  18 Dec 11 13:09 7.3 -> /usr/local/opt/php
````

**Comment by frederickjh** [comment]
I got `phpenv` setup with the help of the maintainer. Drush now runs with the correct version of PHP but even though `drush status` shows it is using the same drush.ini file as before, it seems that the php settings in that file are not being used. I have `disable_functions = ""` set in the drush.ini. However I am getting errors as it is going back to the restrictive settings in the main php.ini file for `disable_functions`.

```bash
 $ drush st
exec() has been disabled for security reasons preflight.inc:398      [warning]
exec() has been disabled for security reasons preflight.inc:443        [warning]
exec() has been disabled for security reasons preflight.inc:398        [warning]
exec() has been disabled for security reasons preflight.inc:398        [warning]
 PHP configuration     :  /opt/cpanel/ea-php56/root/etc/php.ini                 
                          /home/username/.drush/drush.ini                         
 PHP OS                :  Linux                                                 
 Drush script          :  /home/username/bin/drush                                
 Drush version         :  8.1.17                                                
 Drush temp            :  /tmp                                                  
 directory                                                                      
 Drush configuration   :  /home/username/.drush/drushrc.php                       
 Drush alias files     :  /home/username/.drush/sitename.aliases.drushrc.php        
```

If I run the site local Drush directly using the path to it instead of using Drush Launcher:
```bash
 $ ../vendor/drush/drush/drush st
 Drupal version         :  6.49                                                                                                              
 Site URI               :  https://example.org                                                                                                 
 Database driver        :  mysql                                                                                                             
 Database hostname      :  localhost                                                                                                         
 Database port          :  3306                                                                                                              
 Database username      :  dbuser                                                                                                      
 Database name          :  dbname                                                                                                   
 Database               :  Connected                                                                                                         
 Drupal bootstrap       :  Successful                                                                                                        
 Drupal user            :                                                                                                                    
 Default theme          :  acquia                                                                                                         
 Administration theme   :  seven                                                                                                             
 PHP executable         :  /home/username/.phpenv/versions/5.6/bin/php                                                                         
 PHP configuration      :  /opt/cpanel/ea-php56/root/etc/php.ini /home/username/.drush/drush.ini                                               
 PHP OS                 :  Linux                                                                                                             
 Drush script           :  /home/username/example.org/current/vendor/drush/drush/drush.php                                                       
 Drush version          :  8.1.17                                                                                                            
 Drush temp directory   :  /tmp                                                                                                              
 Drush configuration    :  /home/username/example.org/current/docroot/sites/default/drushrc.php /home/username/example.org/current/drush/drushrc.php 
                           /home/username/.drush/drushrc.php                                                                                   
 Drush alias files      :  /home/username/.drush/sitename.aliases.drushrc.php                       
 Install profile        :  default                                                                                                           
 Drupal root            :  /home/username/example.org/current/docroot                                                                            
 Drupal Settings File   :  sites/default/settings.php                                                                                        
 Site path              :  sites/default                                                                                                     
 File directory path    :  sites/default/files                                                                                               
 Temporary file         :  /tmp/username/example.org                                                                                             
 directory path                                             
```
All is well and it finds the Drupal site.

**Comment by webflo** [comment]
> So, I am not sure why went using the drush-launcher that the drush.ini is ignored.

This is because drush-launcher skips some parts of the drush bootstrap process (DRUSH_PHP, PHP_OPTIONS etc). Drush launcher includes a few php files, it does not open a new php process with new configuration. See https://github.com/drush-ops/drush-launcher/blob/master/bin/drush.php#L144

Could you try "php -d disable_functions="" $(which drush) st"?

**Comment by frederickjh** [comment]
`php -d disable_functions="" $(which drush) st` runs without the errors, but the Drupal site is not seen by drush even though I am in the Drupal root.

```bash
$ php -d disable_functions="" $(which drush) st
 PHP configuration      :  /opt/cpanel/ea-php56/root/etc/php.ini /home/username/.drush/drush.ini                                
 PHP OS                 :  Linux                                                                                              
 Drush script           :  /home/username/bin/drush                                                                             
 Drush version          :  8.1.17                                                                                             
 Drush temp directory   :  /tmp                                                                                               
 Drush configuration    :  /home/username/.drush/drushrc.php                                                                    
 Drush alias files      :  /home/username/.drush/sitename.aliases.drushrc.php
```
It is running the site local Drush (version 8.1.17) as my falback Drush version is version 8.1.18.

I did not have a `autoload.php` in the Drupal root. I added one base on one from another site and then traced back through the files to see that it should load a file. However this too also throws the errors about exec() being disabled.

**Comment by weitzman** [comment]
Too old, and not beyond the scope of the launcher.
