### ISSUE TITLE
Commands are not interactive

### ISSUE THREAD

**Issue by prudloff-insite** [drush-ops/drush-launcher#74]
Hello,

When using Drush 9.6.2 on Linux with an SSH alias, commands are interactive.
However, when calling it through Drush Launcher 0.6.0, commands are not interactive.

It seems this is caused by XdebugHandler: https://github.com/drush-ops/drush-launcher/blob/74f678ea17e6ab8135439d17db9e636dd8692f87/bin/drush.php#L123

Before, `posix_isatty(STDOUT)` returns true and after, it returns false.
Would it be possible to tell XdebugHandler that we are using a TTY?

**Comment by weitzman** [comment]
I wonder how Composer gets around this (they also use XdebugHandler). Does it have interaction in require or update commands?

**Comment by prudloff-insite** [comment]
I had another look at the Drush code and it seems this was fixed recently: https://github.com/drush-ops/drush/commit/dda3993778f6d81e339d1ae7f0b1c8e18cc9b573

The problem was that `TerminalUtils::isTty()` relied only on `posix_isatty()` whereas `Input::isInteractive()` (also used by Composer) is more reliable.
