### ISSUE TITLE
`drush --version` reporting incorrect Drush Launcher version for version 0.7.3

### ISSUE THREAD

**Issue by lpeabody** [drush-ops/drush-launcher#80]
```
docker@cli:~$ curl -fsSL "https://github.com/drush-ops/drush-launcher/releases/download/0.7.3/drush.phar" -o ./drush-launcher
docker@cli:~$ chmod a+x drush-launcher 
docker@cli:~$ ./drush-launcher --version
Drush Launcher Version: 0.7.2
 Drush Version   :  8.3.5 
```

Just wanted to point this out in case it hasn't been noticed!

**Comment by webflo** [comment]
This is probably because we had some issues with Travis CI during the last release. Version 0.7.2 and 0.7.3 have the same git revision.

**Comment by lpeabody** [comment]
@webflo thanks for the context. Do you expect this to be a possibly recurring issue? If its not then I can just add an exception for this one case in our tests which validate expected versions of software are installed.

**Comment by webflo** [comment]
@lpeabody I resolved, the issue and it should not occur again. I publish a new release later today.

**Comment by webflo** [comment]
New release https://github.com/drush-ops/drush-launcher/releases/tag/0.7.4

**Comment by lpeabody** [comment]
Thanks @webflo!
