### ISSUE TITLE
Huge memory use in drush launcher 0.8.0 (Out of memory kill during drush si)

### ISSUE THREAD

**Issue by rfay** [drush-ops/drush-launcher#82]
On Drupal 9.1.x, using drush launcher to run site-installed drush:

```
# Running 'drush si' to install drupal....
# 
# mmap() failed: [12] Cannot allocate memory
# 
# mmap() failed: [12] Cannot allocate memory
# 
# mmap() failed: [12] Cannot allocate memory
# PHP Fatal error:  Out of memory (allocated 4297068544) (tried to allocate 8589934600 bytes) in phar:///usr/local/bin/drush/.box/src/Printer.php on line 61
```

Why is drush launcher trying to use all that memory in Printer.php?

I think I can work around this in quicksprint by just running vendor/bin/drush, but had hoped not to see this kind of behavior change.

**Comment by webflo** [comment]
Could you try this with version https://github.com/drush-ops/drush-launcher/releases/tag/0.7.4?

**Comment by rfay** [comment]
This may be a drush 8.4.5 issue, trying to make a way to repro it.

Although it happens *always* in CI on [quicksprint](https://github.com/drud/quicksprint) https://github.com/drud/quicksprint/pull/183 I'm having a hard time making it happen manually (even ssh-ing into circleci). 

I thought that we were still composer-installing drush in quicksprint, but I guess the 8.4.x support for D9 let us remove that. So we're actually using drush launcher with drush 8 to do this drush si.

**Comment by rfay** [comment]
I have some answers.

1. drush8 does the `drush si` just fine with no issues, so that's what I committed to fix this problem. See [code](https://github.com/drud/quicksprint/blob/f7ae73883181608ea33533a6e8ba6d99ffa10dab/start_sprint.sh#L49-L50)
2. drush launcher 0.7.4 also does just fine with no issues. I made a test PR to take a look, https://github.com/drud/quicksprint/pull/189
3. drush launcher 0.8.0 results in the OOM kill every single time on both Linux and macOS (although somehow it doesn't on Windows, perhaps different terminal IO handling?). The test PR is https://github.com/drud/quicksprint/pull/188, and the failing test on CircleCI is https://app.circleci.com/pipelines/github/drud/quicksprint/175/workflows/df4ffdaf-8ff0-44a1-ba39-de974dad51a5/jobs/2919 - the test failure on macOS is identical. See the [test](https://app.circleci.com/pipelines/github/drud/quicksprint/175/workflows/df4ffdaf-8ff0-44a1-ba39-de974dad51a5/jobs/2919) and the failure reported in that test is

```
# drupal/drupal: This package is meant for core development,
#                and not intended to be used for production sites.
#                See: https://www.drupal.org/node/3082474
# 
# Running 'drush si' to install drupal....
# 
# mmap() failed: [12] Cannot allocate memory
# 
# mmap() failed: [12] Cannot allocate memory
# 
# mmap() failed: [12] Cannot allocate memory
# PHP Fatal error:  Out of memory (allocated 4297068544) (tried to allocate 8589934600 bytes) in phar:///usr/local/bin/drush/.box/src/Printer.php on line 61
# 
# Fatal error: Out of memory (allocated 4297068544) (tried to allocate 8589934600 bytes) in phar:///usr/local/bin/drush/.box/src/Printer.php on line 61
# Failed to execute command drush si --yes standard --account-pass=admin --db-url=mysql://db:db@db/db --site-name='Drupal Contribution Time': exit status 255
```

**Comment by rfay** [comment]
Updated results in https://github.com/drud/quicksprint/pull/188#issuecomment-728035488 using `drush si -vvv`

**Comment by csandanov** [comment]
I stumbled onto the same memory issue with 0.8.0, rollback to 0.7.4 resolved it

**Comment by webflo** [comment]
Found the bug. See https://github.com/box-project/box/issues/512

**Comment by webflo** [comment]
@rfay @csandanov fixed in https://github.com/drush-ops/drush-launcher/releases/tag/0.9.0

Thanks for the bug reports!

**Comment by rfay** [comment]
Glad you got it fixed, congratulations.
