### ISSUE TITLE
PHP 8 / PHAR Updater is abandoned

### ISSUE THREAD

**Issue by gapple** [drush-ops/drush-launcher#84]
The `padraic/phar-updater` package and one of its dependencies are abandoned.  The dependency is not marked as compatible with PHP 8, preventing drush-launcher from running:

```
$ drush status

Box Requirements Checker
========================

> Using PHP 8.0.0
> PHP is using the following php.ini file:
  /usr/local/etc/php/8.0/php.ini

> Checking Box requirements:
  ..E.........


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The package "padraic/humbug_get_contents" requires the version "^5.3 || ^7.0
   || ^7.1 || ^7.2" or greater.
```

**Comment by webflo** [comment]
Sadly there is no official/obvious replacement for the self-update command because padraic/phar-updater was abandoned without a replacement. 

We either have to "inline" the code or get rid of the self-update command and recommend other solutions for updating a phar file like https://phar.io/

**Comment by dravenk** [comment]
I added it to my Dockerfile but unfortunately, it doesn't work.
```
    wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar \
    && chmod +x /usr/local/bin/drush
```
The following commands still work. Hope it can be work for you.
```
./vendor/bin/drush
```

**Comment by dravenk** [comment]
If you still want to use the drush command, you can add it to the alias as a temporary solution. We still expect the matter to be fully resolved.
```
echo "alias drush='./vendor/bin/drush'" >> ~/.bashrc
source ~/.bashrc
```

**Comment by webflo** [comment]
Fixed in https://github.com/drush-ops/drush-launcher/releases/tag/0.9.0
