### ISSUE TITLE
Support alias groups

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush-launcher#89]
Bask in drush 8 you could have an alias that was a group of other aliases.  In drush 10 I could make a similar alias but it does nothing useful.  For example in a file: all.site.yml
```
live:
  site-list:
    - '@site1'
    - '@site2'
```

It would be useful if the launcher could recognise an alias like this and run the command on each site in turn.

**Comment by weitzman** [comment]
This is out of scope, sorry. See xargs or parallel https://unix.stackexchange.com/questions/104778/gnu-parallel-vs-i-mean-background-vs-xargs-p
