### ISSUE TITLE
Enabling xdebug breaks drush php via the launcher

### ISSUE THREAD

**Issue by chx** [drush-ops/drush-launcher#90]
When launching via the launcher phar, Psy has no prompt and the arrows are broken:

![2021-03-25 22_30_32-Window](https://user-images.githubusercontent.com/193045/112586856-c516bd00-8db9-11eb-8b98-7848a972103c.png)

and @webflo says DRUSH_ALLOW_XDEBUG=1 drush php works and it _does_ so there's something about re-bootstrapping without xdebug here.

**Comment by leymannx** [comment]
Is it only `drush php`? All other commands are working? `drush cr`? Your environment is what exactly? OS? Psyshell version? PHP version? OS version? In what directory are you executing the command?

**Comment by chx** [comment]
Yes, everything is working. Even `drush php` itself is working it's just the readline / prompt functionality that's broken. Some terminal issues. I am using the Windows Terminal. I checked and  $_SERVER['TERM'] is the same for both launcher and vendor/bin/drush, `xterm-256color`. It'll be something else... but since Psy\Info() is not working, I have a bit of a hard time figuring out what.

**Comment by chx** [comment]
I found the launcher adds `--ansi` to the command but if I manually add it , that doesn't break. I am available for videocalls :)

**Comment by chx** [comment]
I checked and it finds the drush version in vendor and the backtraces are the same. However, $_SERVER is vastly different. While capturing with `drush php |tee launcher-drush.txt` and  `vendor/bin/drush php |tee vendor-drush.txt ` I found I can repro the behavior with the latter command!! 

tee breaks Windows Terminal? Wut?

**Comment by chx** [comment]
I am closing this as this is not the launcher's fault. I can repro with `psysh|tee`.

**Comment by chx** [comment]
Re-closing this and moving on to xdebug-handler.

**Comment by chx** [comment]
This will be solved by https://github.com/drush-ops/drush-launcher/issues/91

**Comment by bobthecow** [comment]
> I am closing this as this is not the launcher's fault. I can repro with `psysh|tee`.

FWIW this (and the broken xdebug-handler forwarding) is happening because newer versions of PsySH detect when STDIN is not a TTY or when STDOUT is redirected, and act differently.

In the case of xdebug-handler, properly forwarding input and output fixes it. In the case of piping to `tee`, you'd probably have to override the automatic detection and explicitly set input/output options on PsySH.
