### ISSUE TITLE
Update xdebug-handler

### ISSUE THREAD

**Issue by chx** [drush-ops/drush-launcher#91]
https://github.com/composer/xdebug-handler/releases/tag/1.4.5 

I cloned the repo and ran `composer require 'composer/xdebug-handler'` in addition to the steps found in the github workflow and the pipe stuff is no longer broken.

![2021-03-27 19_41_16-Window](https://user-images.githubusercontent.com/193045/112740760-82c5bb00-8f34-11eb-9643-b92fcc4a4e41.png)

**Comment by weitzman** [comment]
I would be in favor of removing this package altogether. xdebug3 is a lot easier to configure so that it can be left on without perf penalty.

**Comment by chx** [comment]
I am just saying, until that issue is resolved, this is a trivial way to get more functionality.
